### ISSUE TITLE
Fix version pinning between Redme and requirements.txt

### ISSUE THREAD

**Issue by mpibpc-mroose** [jungmannlab/picasso#34]
Hi all,
in the ReadMe there is `matplotlib==1.5.1` mentioned as requirements, but in your `requirements.txt` no version pinning occurs. So this has to be fixed.

Additionally the PyQt4 requirement is missing in `requirements.txt`.

**Comment by aaristov** [comment]
PyQt4 and matplotlib are not available via pypi, so you have to install it via conda install.

**Comment by straussmaximilian** [comment]
Hi, thanks for pointing this out. The version pinning and the additional install via conda while having a requriemtens.txt is indeed not satisfactory. 

In the future, there will be a bigger update from PyQt4 to PyQt5 (which is installable via pip) plus I'll fix the compatibility issues for matplotlib so that a complete install via requirements.txt should be possible.

**Comment by straussmaximilian** [comment]
Version pinning now maintained with dependabot.
