### ISSUE TITLE
RCC Drift correction fails

### ISSUE THREAD

**Issue by preynoldssco** [jungmannlab/picasso#4]
![image](https://user-images.githubusercontent.com/12394236/37907272-7f10df74-30fc-11e8-86cb-9ff96ed240f3.png)

After fitting, I can't apply drift correction in Render module.
Should I be setting up picks or segmentation before running drift correction?

locs file:
https://gla-my.sharepoint.com/:u:/g/personal/paul_reynolds_glasgow_ac_uk/EYVpKeE6fT9MrINQAnNJ2zoBlCqp9aK2tiwejKF03A12DQ?e=Enbg9M

win10, in anaconda environment as in readme.

**Comment by straussmaximilian** [comment]
Hi,
I tried to reproduce the error but unfortunately wasn't able to reproduce on Linux and Windows.
<img width="967" alt="screen shot 2018-03-26 at 3 31 55 pm" src="https://user-images.githubusercontent.com/16521288/37909336-e2281ccc-310a-11e8-82c4-6a9d41f3debe.png">

The recommended approach is to use RCC with default settings (1000). If it should fail adjust (usually increase) with respect to number of locs/frame in order to be able to correlate. Then pick markers (e.g. beads / Au-Np or DNA-origami) and use undrift by pick.

Which segmentation parameter did you choose?
From the error message it looks like the progress bar is failing to initialize, but that should not even be the case if the segmentation parameter is wrongly chosen.

**Comment by preynoldssco** [comment]
Looks good on your system!

I've tried small and large segmentation parameter values with the same error. (1,500,1000,5000,10000,20000,50000) - so I think it's failing before that.

I'll rebuild the environment again? It's possible I've made a mistake along the way, but I've had this same error on two machines.

**Comment by straussmaximilian** [comment]
Hmm. At this point I can only imagine some package incompatibility.
Can you quickly verify your tqdm version? Should be 4.18.8. 
Try conda list:
<img width="421" alt="screen shot 2018-03-26 at 4 34 05 pm" src="https://user-images.githubusercontent.com/16521288/37912786-8a7d574a-3113-11e8-906e-97a53a46975a.png">

You can try to install the tqdm package again:
conda: conda install -c conda-forge tqdm or
pip: pip install tqdm

Let me know whether that helped. Thanks.

**Comment by preynoldssco** [comment]
That's the one - updated tqdm and that's fixed it thanks! Drift correction now OK, progress bar and all

For reference, this was my package list after my attempt at setting things up:
![image](https://user-images.githubusercontent.com/12394236/37914611-82a944d8-310f-11e8-992f-93a641ecce43.png)

**Comment by straussmaximilian** [comment]
Great! Happy that it works now. Will place a little note in the readme.

**Comment by preynoldssco** [comment]
Thanks

Another small edit for the readme is that activating the environment is different on windows/mac

Mac:
source activate picasso

Windows:
activate picasso




--
Paul Reynolds, Biomedical Engineering
University of Glasgow

Paul.Reynolds@Glasgow.ac.uk
+44 141 330 6691

Google Scholar: https://goo.gl/0yRpwg
ResearchGate:  http://goo.gl/9lyQq1

________________________________

**Comment by straussmaximilian** [comment]
Will change. Thanks
